import os
import google.generativeai as genai
from dotenv import load_dotenv
from kg_rag_engine import KGRAGEngine # From Task 1

# Load your API key from the .env file
load_dotenv()
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

class NmapAgent:
    def __init__(self):
        self.brain = KGRAGEngine()
        # We use Gemini 1.5 Flash for fast and smart classification
        self.classifier_model = genai.GenerativeModel('gemini-2.5-flash')
        
    def classify_complexity(self, intent):
        """Uses Google Gemini to decide if the task is Easy, Medium, or Hard."""
        prompt = f"""
        Analyze the following Nmap scanning intent and classify its complexity as 'Easy', 'Medium', or 'Hard'.
        
        - Easy: Simple port scans, ping scans, or basic host discovery.
        - Medium: Service detection, OS detection, or specific timing/stealth flags.
        - Hard: Vulnerability scanning, custom scripts, or complex multi-step reconnaissance.
        
        Intent: "{intent}"
        
        Respond with ONLY the word: Easy, Medium, or Hard.
        """
        
        try:
            response = self.classifier_model.generate_content(prompt)
            complexity = response.text.strip()
            # Ensure the response is one of our expected categories
            if complexity in ["Easy", "Medium", "Hard"]:
                return complexity
            return "Medium" # Default if Gemini gives a weird answer
        except Exception as e:
            print(f"Error talking to Gemini: {e}")
            return "Easy" # Fallback

    def diffusion_synthesis(self, intent, target):
        """The 'Creative Thinker' for Hard tasks (same as before)."""
        print("--- Starting Diffusion Synthesis (Iterative Refinement) ---")
        current_guess = f"nmap -A -T4 --script=vuln {target}"
        
        for attempt in range(3):
            print(f"Attempt {attempt + 1}: {current_guess}")
            validation = self.brain.validate_command(current_guess, is_root=True)
            
            if validation["is_valid"]:
                return current_guess
            else:
                print(f"Refining due to error: {validation['errors'][0]}")
                current_guess = current_guess.replace("-A", "-sV") 
        return current_guess

    def handle_request(self, intent, target):
        # Now using Gemini for classification!
        complexity = self.classify_complexity(intent)
        print(f"\n[Manager] Gemini classified this as: {complexity}")
        
        if complexity == "Easy":
            return self.brain.generate_zero_shot([intent], target)
        elif complexity == "Medium":
            return f"nmap -sS -sV {target} (Generated by Specialist)"
        elif complexity == "Hard":
            return self.diffusion_synthesis(intent, target)

# --- Testing the Smart Manager ---
if __name__ == "__main__":
    agent = NmapAgent()
    
    # Test 1: Gemini should see this as Easy
    print(f"Result: {agent.handle_request('just check if the host is up', '192.168.1.1')}")
    
    # Test 2: Gemini should see this as Medium
    print(f"Result: {agent.handle_request('find out what OS and services are running', 'example.com')}")
    
    # Test 3: Gemini should see this as Hard
    print(f"Result: {agent.handle_request('run a full vulnerability assessment with custom scripts', '10.0.0.1')}")